baseURL = "https://junbowang.com"
title = "Junbo Wang"
theme = "PaperMod"
paginate = 10
enableRobotsTXT = true

[params]
  description = ""
  author = "Junbo Wang"
  defaultTheme = "auto"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = false
  ShowToc = false
  disableHLJS = true

  [params.cover]
    linkFullImages = false
    responsiveImages = false

[[menu.main]]
  name = "CV"
  url = "https://www.dropbox.com/scl/fi/p98r4pefq2setgxfhjt1a/CV.pdf?rlkey=8bn6sshdhi9acre3lm35u3248&dl=0"
  weight = 1

[[menu.main]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/wang-junbo-2000"
  weight = 2

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/junbo-wang-plus"
  weight = 3

[[menu.main]]
  name = "Instagram"
  url = "https://www.instagram.com/bread19000"
  weight = 4
